### ISSUE TITLE
Use a different time input?

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#3041]
08:00 is invalid (option for 24hour?)

Backspace doesn't work so appears as though the field isn't working.

All times must be selected.
Type 7:00 PM and it'll appear valid, it shows the time below for you to select. Just press enter and nothing happens, tab away and the time will switch back to whatever was set before. 

To select a time you enter it and either click the exact same time you just entered or press enter. We've had many users commenting on the current editor and the fact that they prefer to enter dates/times manually which is fine if they want to but with the new EDTR is frustrating.

**Comment by tn3rb** [comment]
@Pebblo 

I've replaced the date and time pickers from Uber with some new ones that hopefully work better. I really didn't like how those other ones worked either so was happy to swap them out. That said, there's not really a huge selection of date and time pickers available that work well, are accessible, and compatible with the libraries we are using, so hopefully these ones will fair better than the last ones.

I've pushed the changes to the `EDTR/production` branch which you can try out locally, or via my dev site: https://brent.eventespresso.com/wp-admin/admin.php?page=espresso_events

**Comment by Pebblo** [comment]
Thanks, Brent.

I think this new one fits better! It does have its own little quirks but at least doesn't appear broken like before (backspace doing nothing and then times getting lost when you typed it in and didn't select it).

Times seem fine, small gripe is that I don't like the clock face popup and think we could get away with nothing at all there but that's more personal preference really. 

I did find an issue that I think will need some attention on the datepicker though:

Edit a datetime and click on the Start Date month....

Select a month and then select an option on the datepicker (notice how the datepicker updates as you select a month).

Now click the month dropdown again, selecting another month, this time the datepicker itself doesn't update with your selection and shows whatever was set last time.

---

The month dropdown appears over the date picker, I suspect this is expected and is to give easy access to changing the months? Not a big issue but I think it looks a little funky like this:

![image](https://user-images.githubusercontent.com/4345417/88289938-e9337300-cced-11ea-8092-dbd89cb54969.png)

**Comment by tn3rb** [comment]
it may be possible to hide the clock popup, as it really does seem pointless doesn't it?

those other issues are internal to this new datepicker component and we won't have any control over fixing them. That said, I can see if there is something funny about the way I've configured it that is causing the problems.

With regards to the month options appearing over top of the calendar... which did you click on last? If you had just clicked on the month selector, wouldn't you expect the month options to appear above the calendar?
Although it appears that part of the issue is that the calendar and the month options are both staying open when maybe only one of them should be.

OH! Important point I forgot to mention...

The formats used for displaying the dates and times are taken directly from the WP Settings page, so if you change those options, then the formatting here should also change. This will also change the nature of how you interact with those inputs, as the select box is only used when the format uses words as opposed to numbers. So changing to a month format like `01-12` should change the datepicker input to just use a text field instead of a dropdown. Can you plz thoroughly test that functionality as well? thnx.

**Comment by Pebblo** [comment]
> With regards to the month options appearing over top of the calendar... which did you click on last?

I'm clicking directly onto the month dropdown and both the dropdown and the datepicker open at the same time.

> If you had just clicked on the month selector, wouldn't you expect the month options to appear above the calendar?

I kinda didn't expect the dropdown to appear at all and just would have set the date through the datepicker. It is a little quicker to be able to do so through the month dropdown and it appearing over the top isn't a big issue.

> Although it appears that part of the issue is that the calendar and the month options are both staying open when maybe only one of them should be.

The bigger issue is you can't 're' set your month using the dropdown, so it's going to cause confusion with some of our users.

If you select July 18th and set the datepicker, then realise you wanted August 18th and open the dropdown/datepicker combo the dropdown no longer updates the datepicker with the selection.

> The formats used for displaying the dates and times are taken directly from the WP Settings page, so if you change those options, then the formatting here should also change. This will also change the nature of how you interact with those inputs, as the select box is only used when the format uses words as opposed to numbers. So changing to a month format like 01-12 should change the datepicker input to just use a text field instead of a dropdown. Can you plz thoroughly test that functionality as well? thnx.

KK, will do. Thanks.

**Comment by Pebblo** [comment]
@tn3rb 

Looking at #3035 it looks like the months dropdown should now be hidden right?

I can still see it locally: 
![image](https://user-images.githubusercontent.com/4345417/89225831-c7ca6500-d5d2-11ea-800b-d172764df160.png)

Same happens on Brents dev site: 
![image](https://user-images.githubusercontent.com/4345417/89226102-44f5da00-d5d3-11ea-9c25-3453ba968f1a.png)

**Comment by Pebblo** [comment]
Testing various date/time formats has been fine and seems to be working as expected.

I'm going to pass this back for the above for now, but will continue testing various setups and see what the datepicker does.

**Comment by tn3rb** [comment]
> Looking at #3035 it looks like the months dropdown should now be hidden right?

hmmmm don't think you linked to the correct PR since #3035 has nothing to do with datepickers

but to answer your question, unfortunately we have not been able to figure out how to hide the dropdown or the calendar from appearing when you click on the month selector. That is controlled from within the datepicker library we are using and there is no way to control that externally. That said, if you choose a new month, the calendar does change correctly which is nice.

**Comment by Pebblo** [comment]
@tn3rb Sorry, I meant to link to #3053

The screenie here: https://github.com/eventespresso/event-espresso-core/pull/3053#issuecomment-664953638

Suggests this is 'fixed' (in a hacky way), did that get removed?

> That said, if you choose a new month, the calendar does change correctly which is nice.

For me that still breaks if I select a month and close the datepicker, then open it again and try to select another month in the dropdown, the datepicker doesn't update.

**Comment by tn3rb** [comment]
closing because the datepicker has been replaced again with the new one having much better text entry capabilities
